### PR TITLE
Meta data update

### PR DESCRIPTION
**Pull request by floyd-fuh**
Just changed some meta data and also would like to do a test run on how a Burp plugin is updated.

Unrelated to this pull request, but also note: I'll soon going to do an organization change to my repository (handing over to the modzero organization) but as far as I understand from https://help.github.com/articles/about-repository-transfers/ this is no big deal, as all references are cleanly updated.

### CODE REVIEW

**Comment by ahri** [comment]
I think that changing ownership over should be fine, if not it's easy enough for us to re-fork the repo later.

**Comment by floyd-fuh** [comment]
Thanks for the pull! However, when I install the app from the BAppStore it's still the old version. I tried everything, from refreshing the list, reinstalling, close and reopen Burp. Is this tagged for a certain Burp release or something? Or maybe it's because I forgot to change the version number to 0.0.2 or something?

**Comment by ahri** [comment]
We're still working on our process, and right now there's a manual step to sign the extension which I personally can't do as I'm not working in the office, so it's in a (short!) queue of extensions that I've vetted, got compiling, etc. and simply need signing. So unless the guy signing them notices something I didn't I'd guess it'll be published later on today (Monday) or tomorrow.

Depending on volume we might consider automating the signing stage, but right now we'd prefer to maintain quality by having two sets of eyes looking at the extensions as we publish them, I hope this makes sense!

**Comment by floyd-fuh** [comment]
Makes sense, thanks for the information!

**Pull request merged**
